project:
  type: website

website:
  search: false
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: blog.qmd
        text: Blog
  draft-mode: unlinked
  page-footer:
    border: false
    center:
      - text: "Â© 2026 Stefan Langenbach"
        href: index.qmd
      - text: "Imprint"
        href: imprint.qmd
      - text: "Privacy Policy"
        href: privacy.qmd

format:
  html:
    theme:
      light: [default, assets/styles/light.scss]
      dark: [default, assets/styles/dark.scss]
